<?php
/*
This class contains functions for routine data operations like loading form data and saving/updating records to database tables.

To interact with a specific database table, create an object that extends this class and whose fields match that tables columns.

DO NOT EDIT THIS FILE - core ORM framework functionality
*/

class data_operations {

  public $table;
  public $id_field;
  public $fields;
  public $values;

  protected $id_value;        // Used internally to store Primary Key Value
  protected $id_field_is_ai;  // Used internally for SQL INSERT vs UPDATE logistics
  protected $id_value_temp;   // Temporary storage for NON-AI id_value before SQL INSERT

  //////////////////////////////////////////////////////////////////////////////////////////////////
  //////////////////////////////////////////////////////////////////////////////////////////////////
  // Constructor
  public function __construct($table, $id_field, $is_ai=true, $fields) {
      $this->table = $table;
      $this->id_field = $id_field;
      $this->fields = $fields;

      foreach ($this->fields as $field){
        $this->values[$field] = '';
      }
      $this->id_field_is_ai = $is_ai;
      $this->id_value = '';
      $this->id_value_temp = '';
  }
  //////////////////////////////////////////////////////////////////////////////////////////////////
  //////////////////////////////////////////////////////////////////////////////////////////////////

  /*
  Getter for protected $id_value
  Will be empty for an object not yet saved to database.
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function get_id_value() {
      return $this->id_value;
  }

  /*
  Setter for protected $id_value
  Use for non-AUTO-INCREMENT Primary Keys (gets automatically done internally for AUTO-INCREMENT PKs)
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function set_id_value($non_ai_id_value) {
      if ($this->id_field_is_ai) {
        $error = "ERROR - ORM FRAMEWORK: Attempting to manually set_id_value() for Auto-Increment Primary Key";
        echo $error;
        exit;
      }
      else {
        // AI field is not Auto-Increment
        if ($this->id_value !== '') {
          $error  = "ERROR - ORM FRAMEWORK: Attempting to set_id_value() that's already populated. ";
          $error .= "Don't change Primary Key value of an Active Record. Load new Active Record";
          echo $error;
          exit;
        }
        else {
          // Insert method copies from temp to actual id_value
           $this->id_value_temp = $non_ai_id_value;
        }
      }
  }

  /*
  Loads a database record as Active Record (AR) given a Primary Key value
  Defaults to loading from Primary Key field.
  Otherwise second argument must give the name of a UNIQUE DB field to load from.
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function load($value, $field = '') {
      if ($value === "") {return;}

      // Defaults to loading from primary key field if no field specified
      if (!$field) {
        $field = $this->id_field;
      }

      $sql = "SELECT * FROM " . $this->table . " WHERE $field = :value";
      $result = lib::db_query($sql, [':value' => $value]);
      $rows = $result->fetchAll();

      if (count($rows) == 1) {
        $row = $rows[0];
        $this->id_value = $row[$this->id_field];
        foreach ($this->fields as $field) {
          $this->values[$field] = $row[$field];
        }
      }
      else if (count($rows) > 1) {
        $error = "ERROR - ORM FRAMEWORK: Attempting to load() a database record resulted in more than one row. ";
        $error .= "Trying to load from a non-unique field?";
        echo $error;
        exit;
      }
      else {
        // 0 rows - null fill the object
        $this->values = array_fill(0, count($this->fields), null);
      }
  }

  /*
  Note:
  Many ORM frameworks have a load_multiple() method, but that's not implemented in this class.
  Given an array of Primary Key values as input, load_multiple() would return an array of Active Records.
  
  Such a method is not included here because more complex data operations such as that are 
  better placed as custom methods in a table-specific class. 
  */

  /*
  Populates $this->values[] with submitted form data whose names match fields in $this->fields[]
  The values for any fields with no incoming form data are left empty since $_REQUEST will be empty
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function load_from_form_submit() {
      $this->id_value = $_REQUEST[$this->id_field];
      foreach ($this->fields as $field) {
        if (is_array($_REQUEST[$field])) {
          // Just load into the object field
          $this->values[$field] = $_REQUEST[$field];
        }
        else {
          // Trim the string
          $this->values[$field] = trim($_REQUEST[$field]);
        }
      }
  }

  /*
  Same as load_from_form_submit() except that only fields with incoming form values
  update the object, leaving other pre-populated object values intact
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function update_from_form_submit() {
      if (isset($_REQUEST[$this->id_field])) {
        $this->id_value = $_REQUEST[$this->id_field];
      }
      foreach ($this->fields as $field) {
        if (isset($_REQUEST[$field])) {
          $this->values[$field] = trim($_REQUEST[$field]);
        }
      }
  }

  /*
  SQL INSERT or UPDATE depending upon whether $this->id_value protected field is populated
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function save() {
      if ($this->id_value === "") {
        if ($this->id_field_is_ai) {
          $this->insert();
        }
        else {
          if($this->id_value_temp === "") {
            echo "ERROR - ORM FRAMEWORK: Use set_id_value() to populate NON Auto-Increment Primary Key before saving object.";
            exit;
          }
          else {
            $this->insert();
          }
        }
      }
      else {
        // id_value is set so do the update
        $this->update();
      }
  }

  /*
  Implements the SQL INSERT for save() method
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  private function insert() {

      $non_pk_field = '';
      $non_pk_value = '';

      if (!$this->id_field_is_ai) {
        // Must add the non-pk field and value to the INSERT statement
        $non_pk_field = $this->id_field . ", ";
        $non_pk_value = ":" . $this->id_field . ", ";
      }

      $query  = "INSERT INTO " . $this->table . " ($non_pk_field";
      $query .= implode(', ', $this->fields);
      $query .= ") VALUES ($non_pk_value";
      $query .= ":" . implode(', :', $this->fields);
      $query .= ")";

      $placehold = [];
      if (!$this->id_field_is_ai) {
        $placehold[':' . $this->id_field] = $this->id_value_temp;
      }
      foreach ($this->fields as $field) {
        $placehold[':' . $field] = $this->values[$field];
      }

      lib::db_query($query, $placehold);

      // After the save, designate $this as an active record
      if ($this->id_field_is_ai) {
        global $pdo;  // need db connection handle visible in this function to do the following
        $this->id_value = $pdo->lastInsertId();
      }
      else {
        $this->id_value = $this->id_value_temp;
      }
  }

  /*
  Implements the SQL UPDATE for save() method
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  private function update() {
      $query = "UPDATE " . $this->table . " SET ";
      foreach ($this->fields as $field) {
        $query .= "$field = :$field, ";
      }
      $query = substr($query, 0, -2); // Remove the trailing ", "
      $query .= " WHERE " . $this->id_field . " = :id_value";

      $placehold = [':id_value' => $this->id_value];
      foreach ($this->fields as $field) {
        $placehold[':' . $field] = $this->values[$field];
      }

      lib::db_query($query, $placehold);
  }

  /*
  Implements SQL DELETE given a primary key value.
  Clears id_value and field values after deletion, leaving the object empty.
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function delete($obj_id) {
      $query = "DELETE FROM " . $this->table . " WHERE " . $this->id_field . " = :id_value";
      lib::db_query($query, [':id_value' => $obj_id]);
  
      $this->id_value = '';
      foreach ($this->fields as $field) {
          $this->values[$field] = '';
      }
  }
  
  /*
  Use before adding object fields to html attributes such as value=""
  Converts reserved characters in HTML quotations to html entities - Example: " becomes &quot;
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function html_safe() {
      if ($this->id_value !== '') {
        $this->id_value = htmlentities($this->id_value,ENT_QUOTES);
      }
      foreach ($this->fields as $field){
        if (!is_null($this->values[$field])){
            $this->values[$field] = htmlentities($this->values[$field],ENT_QUOTES);
        }
      }
  }

  /*
  Converts html entities like &quot; back to the ASCII character
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function html_unsafe() {
      if ($this->id_value !== '') {
        $this->id_value = html_entity_decode($this->id_value,ENT_QUOTES);
      }
      foreach ($this->fields as $field){
        if (!is_null($this->values[$field])){
            $this->values[$field] = html_entity_decode($this->values[$field],ENT_QUOTES);
        }
      }
  }

  /*
  Saves the Active Record object to PHP SESSION as an associative array
  Field names are prefixed (sess_) so the SESSION keys are like sess_my_DB_column
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function save_to_session($prefix="sess_") {
      $_SESSION[$prefix.$this->id_field] = $this->id_value;
      foreach ($this->fields as $field) {
        $sess_fieldname = $prefix.$field;
        $_SESSION[$sess_fieldname] = $this->values[$field];
      }
  }

  /*
  Loads an Active Record object that has been saved into SESSION by save_to_session()
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function load_from_session($prefix="sess_") {
      $this->id_value = $_SESSION[$prefix.$this->id_field];
      foreach ($this->fields as $field) {
        $sess_fieldname = $prefix.$field;
        $this->values[$field] = $_SESSION[$sess_fieldname];
      }
  }

  /*
  Wipes an Active Record object that has been saved to SESSION
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function wipe_from_session($prefix="sess_") {
      unset($_SESSION[$prefix.$this->id_field]);
      foreach ($this->fields as $field) {
          $sess_fieldname = $prefix.$field;
          unset($_SESSION[$sess_fieldname]);
      }
  }

  /*
  Writes all Active Record object fields to hidden form elements
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function hide_in_form() {
      $this->html_safe();
      echo '<input type="hidden" name="'.$this->id_field.'" value="'.$this->id_value.'">'."\n";
      foreach ($this->fields as $field) {
        echo '<input type="hidden" name="'.$field.'" value="'.$this->values[$field].'">'."\n";
      }
      $this->html_unsafe();
  }

  /*
  Recovers all Active Record object fields from hidden form element
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function load_from_hidden() {
      $this->id_value = $_REQUEST[$this->id_field];
      foreach ($this->fields as $field) {
        $value = $_REQUEST[$field];
        $this->values[$field] = $value ;
      }
      $this->html_unsafe();
  }

  /*
  Loads potentially many records from a table into a MySQL result set.
  Optional Parameters:
    $sortby for MySQL ORDER BY field
    $sortorder for MySQL ORDER BY direction
    $where_clause for MySQL WHERE filtering
      Example: $obj->load_table('created_at', 'DESC', "status = 'active' OR status = 'pending'");
      CAUTION: This does not guard against SQL injection. Don't put user-entered values into $where_clause.
  CAUTION: Without $where_clause, loads an entire table. Avoid on large tables.
  */
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  public function load_table($sortby='', $sortorder="ASC", $where_clause='') {

    if ($sortby == '') {
        $sortby = $this->id_field;
    }

    $query  = "SELECT " . $this->id_field . ",";
    $query .= implode(',', $this->fields);
    $query .= " FROM " . $this->table;

    if ($where_clause !== '') {
        $query .= " WHERE " . $where_clause;
    }
    $query .= " ORDER BY " . $sortby . " " . $sortorder;

    return lib::db_query($query, []);
  }


} //end CLASS data_operations

?>
